language: node_js
node_js:
  - 14
jobs:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode7.2
